# ==========================================
# STAGE 1: Local Development install
# ==========================================
ARG NODE_VERSION=lts-alpine3.22

# Define the baseimage
FROM node:${NODE_VERSION} AS installer

# Set workdir
WORKDIR /app

# Copy dependency definitions first
COPY package.json package-lock.json ./

# Calculate hash of the lockfile, compare with previous cache, install only if changed
RUN --mount=type=cache,target=/root/.npm \
    if [ -f /app/node_modules/.package-lock.hash ] && \
       echo "$(sha256sum package-lock.json)" | cmp -s - /app/node_modules/.package-lock.hash; then \
         echo "Dependencies unchanged. Skipping npm install."; \
    else \
         echo "Dependencies changed. Running npm install..."; \
         npm ci && \
         sha256sum package-lock.json > /app/node_modules/.package-lock.hash; \
    fi

# ==========================================
# STAGE 2: Local Development Runner
# ==========================================
FROM  node:${NODE_VERSION} AS runner

# Set workdir
WORKDIR /app

# Copy installed node_modules (including the hash file) from Stage 1
COPY --from=installer /app/node_modules ./node_modules

# Copy project into container
COPY . .

# Port mapping
EXPOSE 3000

# Run the app
CMD ["npm", "run", "dev"]